services:
  demo-webapp:
    profiles: ["demo", "full"]
    build:
      context: ./apps/demo-webapp
      dockerfile: Dockerfile
    container_name: demo-webapp
    ports:
      - "8088:80"
    volumes:
      - nginx_logs:/var/log/nginx
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    restart: unless-stopped

  log-generator:
    profiles: ["demo", "full"]
    build:
      context: ./apps/log-generator
      dockerfile: Dockerfile
    container_name: log-generator
    environment:
      TARGET_URL: http://demo-webapp
      INTERVAL_SEC: "0.8"
    depends_on:
      demo-webapp:
        condition: service_healthy
    restart: unless-stopped

  sentinel:
    profiles: ["engine", "core", "full"]
    build:
      context: ./log-sentinel
      dockerfile: Dockerfile
    container_name: log-sentinel-engine
    working_dir: /app
    command: ["python", "sentinel.py"]
    ports:
      - "8000:8000"
    volumes:
      - ./log-sentinel:/app
      - nginx_logs:/var/log/nginx:ro
    depends_on:
      demo-webapp:
        condition: service_healthy
    restart: unless-stopped

  prometheus:
    profiles: ["observability", "full"]
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    restart: unless-stopped

  grafana:
    profiles: ["observability", "full"]
    image: grafana/grafana:11.2.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
      GF_SECURITY_ALLOW_EMBEDDING: "true"
    volumes:
      - ./infra/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./infra/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  nginx_logs:
